import React from 'react';
import { ArticleLayout } from '../common/Layout';

const Article = () => {
    return (
        <ArticleLayout header="Article 1" footer="3.2.2018 v Praze">
            <p className="text-justify">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Fusce dui leo, imperdiet in, aliquam sit amet, feugiat eu, orci. Mauris elementum mauris vitae tortor. Aenean vel massa quis mauris vehicula lacinia. Vivamus ac leo pretium faucibus. Nulla turpis magna, cursus sit amet, suscipit a, interdum id, felis. Nulla est. Aliquam erat volutpat. Pellentesque ipsum. Fusce nibh. Aliquam in lorem sit amet leo accumsan lacinia. Aenean fermentum risus id tortor. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Nullam at arcu a est sollicitudin euismod. Maecenas sollicitudin. Aenean placerat.</p>

            <p className="text-justify">Et harum quidem rerum facilis est et expedita distinctio. Maecenas ipsum velit, consectetuer eu lobortis ut, dictum at dui. Aenean id metus id velit ullamcorper pulvinar. Vivamus luctus egestas leo. Etiam posuere lacus quis dolor. Duis sapien nunc, commodo et, interdum suscipit, sollicitudin et, dolor. Fusce suscipit libero eget elit. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Phasellus faucibus molestie nisl. Aenean id metus id velit ullamcorper pulvinar.</p>

            <p className="text-justify">Duis ante orci, molestie vitae vehicula venenatis, tincidunt ac pede. Praesent dapibus. Nunc dapibus tortor vel mi dapibus sollicitudin. Suspendisse nisl. Aenean fermentum risus id tortor. Aliquam ornare wisi eu metus. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. Nunc auctor. Phasellus faucibus molestie nisl. Maecenas fermentum, sem in pharetra pellentesque, velit turpis volutpat ante, in pharetra metus odio a lectus. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Duis ante orci, molestie vitae vehicula venenatis, tincidunt ac pede. Phasellus rhoncus. In sem justo, commodo ut, suscipit at, pharetra vitae, orci. Pellentesque sapien. Integer in sapien.</p>

            <p className="text-justify">Pellentesque arcu. Curabitur bibendum justo non orci. Phasellus enim erat, vestibulum vel, aliquam a, posuere eu, velit. Mauris tincidunt sem sed arcu. Nullam rhoncus aliquam metus. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Nullam rhoncus aliquam metus. Quisque tincidunt scelerisque libero. Pellentesque pretium lectus id turpis. Integer pellentesque quam vel velit. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Maecenas ipsum velit, consectetuer eu lobortis ut, dictum at dui. In dapibus augue non sapien. Nulla non lectus sed nisl molestie malesuada. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Nulla non arcu lacinia neque faucibus fringilla. Nam sed tellus id magna elementum tincidunt.</p>

            <p className="text-justify">Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Duis condimentum augue id magna semper rutrum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nulla est. Quisque tincidunt scelerisque libero. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. In convallis. Mauris elementum mauris vitae tortor. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Mauris elementum mauris vitae tortor. Integer imperdiet lectus quis justo. Pellentesque sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Duis sapien nunc, commodo et, interdum suscipit, sollicitudin et, dolor. Nunc dapibus tortor vel mi dapibus sollicitudin. Maecenas lorem. Phasellus rhoncus.</p>
        </ArticleLayout>
    )
};


export default Article;